### ISSUE TITLE
Add r/kiwix

### ISSUE THREAD

**Issue by Popolechien** [anvaka/map-of-reddit-data#1]
A very small subreddit (89 members), so I don't know if it meets any kind of threshold but would be curious to see where it sits.

Thanks, very cool project!

**Comment by anvaka** [comment]
Do you have a suggestion where it should be?

**Comment by Popolechien** [comment]
Well to be honest I asked because I wanted to see where it would end up. But the subredddit that most often mentions it would be r/datahoarders,

**Comment by anvaka** [comment]
With small subreddits I didn't capture enough data to create meaningful relationships. They need to be manually placed. In case of `/r/kiwix` the data suggested with a very low scores the following top 5 related subreddits:

* IllinoisMuslims x 6.98
* MissouriMuslims x 6.98
* WesternCanadaMuslims x 6.71
* ArkansasMuslims x 6.46
* tinkerboard x 6.23

I don't think we can trust this recommendation as it is based only on 13 unique commenters in the captured data

**Comment by anvaka** [comment]
Gave you primary spot here:

![image](https://user-images.githubusercontent.com/225407/113466955-b69d5680-93f4-11eb-8de8-76951b82025f.png)

It is tiny, but it exists! Sincerely wish your subreddit success!

PS: Commit that added it is here: https://github.com/anvaka/map-of-reddit-data/commit/825151d76510389971ee182caa18cd68f6fecc44
