### ISSUE TITLE
Request to add r/Comtruise subreddit

### ISSUE THREAD

**Issue by brmlyklr** [anvaka/map-of-reddit-data#12]
I would like to request that the r/Comtruise subreddit be added to the map of reddit.

**Comment by anvaka** [comment]
Do you have a suggestion where should this be placed and what are some related subreddits?

**Comment by brmlyklr** [comment]
> 
> 
> Do you have a suggestion where should this be placed and what are some related subreddits?

It should be placed near r/synthwave and should be most closely related to r/synthwave, r/newretrowave, and r/chillwave

**Comment by anvaka** [comment]
Thank you! Should be there now
