### ISSUE TITLE
Adding r/FortSaskatchewan

### ISSUE THREAD

**Issue by GlitchedGamer** [anvaka/map-of-reddit-data#13]
Please can you add r/FortSaskatchewan to the Canadian section of the map? Fort Saskatchewan is a city near Edmonton, in the province of Alberta, so r/FortSaskatchewan should be placed near r/Edmonton and r/Alberta. Thank you!

https://www.reddit.com/r/FortSaskatchewan/

**Comment by anvaka** [comment]
Done! Thank you
