### ISSUE TITLE
Add subreddit r/ohtaigi

### ISSUE THREAD

**Issue by jambao24** [anvaka/map-of-reddit-data#5]
Tried following the instructions in the README.md, had difficulties configuring scour. When I tested the "new" version with 'npm run start', I wasn't able to see the newly generated .svg file (got an "XML error"). I'm sure other community members with more experience with these tools can figure out how to do this correctly. Just wanted to give other data science n00bs and laypeople a heads up.

**Comment by anvaka** [comment]
Thank you for the heads up and the request. This should be added now
